---
title: "Geospatial"
author: "Mathieu Pruvot"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(sf)
library(raster)
library(ggplot2)
library(curl)
library(scales)


# House keeping to setup data from the vector chapter
ak_regions <- read_sf("data/ak_regions_simp.shp")

ak_regions_3338 <- ak_regions %>%
  st_transform(crs = 3338)

pop <- read.csv("data/alaska_population.csv")

pop_4326 <- st_as_sf(pop, 
                  coords = c('lng', 'lat'),
                  crs = 4326,
                  remove = F)

pop_3338 <- st_transform(pop_4326, crs = 3338)

 pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)


lc_3338 <- raster("/home/shares/scientist/ds-workshop/ak_nlcd_2011_landcover_50m_3338.tif")

lc_3338
```

plotting the raster
```{r}
plot(lc_3338)
plot(pop_3338,add=T)
```

```{r}
raster_points <- extract(lc_3338, pop_3338, buffer=500, fun=modal)
pop_joined$land_cover <- raster_points
```

loading legend:
```{r}
# Read the land cover legend
legend_lc <- read.csv("/home/shares/scientist/ds-workshop/legend_ak_nlcd_2011.csv", stringsAsFactors = FALSE)
legend_lc
```

recategorize the lc layer
 
```{r}
# It is a lot of categories, let us consolidate this
legend_lc <- legend_lc %>%
  mutate(main_lc = ifelse(ID %in% 40:49, "Forest",
                              ifelse(ID %in% 20:29, "Urban",
                                     ifelse(ID %in% 50:59, "Shrub",
                                             ifelse(ID %in% 70:79, "Grass",
                                                     ifelse(ID %in% 80:89, "Crops",
                                                             ifelse(ID %in% 90:99, "Wetland", Land.Cover.Type)
                                                             )
                                                     )
                                             )
                                     )
                              )
  )


# Join the LC categories to the population data
pop_3338_cover <- left_join(pop_joined, legend_lc, by=c("land_cover"="ID")) %>% 
  dplyr::select(-Red, -Green, -Blue, -Land.Cover.Type)
```
 
```{r}
# Create color palette by keeping last color of each group
pal <- legend_lc %>% 
  group_by(main_lc) %>% 
  slice(n()) %>% # Keeping the last color of the groups
  ungroup %>% 
  arrange(ID) %>%
  mutate(color_hex = rgb(Red, Green, Blue, max = 255)) %>% 
  dplyr::select(main_lc, color_hex)

# turn pallete into a list for plotting
pal_list <- pal$color_hex
names(pal_list) <- pal$main_lc #provides the name of the landcover instead of the color name


# Plot by region
ggplot(pop_3338_cover, aes(region, population, fill = main_lc)) +
    geom_col() +
    scale_y_continuous(labels = comma) +
    scale_fill_manual(values = pal_list) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Land cover type by region and population") +
    labs(fill = "", y = "Population", x = "")
```
```{r}
ggplot() +
    geom_sf(data = ak_regions_3338, aes(), color = "black") +
    geom_sf(data = pop_3338_cover, aes(color = main_lc,
                                       size = population), show.legend = "point") +
    scale_size_continuous(guide = F) +
    scale_color_manual(values = pal_list) +
    theme_bw() +
    theme(legend.position = "bottom", legend.title = element_blank())
```
```{r}
copper_region_3338 <-  ak_regions_3338 %>% 
  filter(region== "Copper River")

plot(copper_region_3338)
```
```{r}
copper_lc_3338 <- crop(lc_3338,copper_region_3338)
plot(copper_lc_3338)
```
Defining forest mask function
If operations need to be made on raster objects, create function to speed up the processing

```{r}
forest_masker <- function(x){
  x[x<40|x>49] <- 0
  x[x>=40 & x<=49] <- 1
  return(x)
}
```

Now apply this function using the raster calc function
```{r}
copper_forested_3338 <- calc(copper_lc_3338,forest_masker)
plot(copper_forested_3338)
```
Selectin the coper river population
```{r}
copper_pop_3338 <- pop_3338_cover %>% 
  filter(region == "Copper River")
```
```{r}
forested_count <- extract(copper_forested_3338,copper_pop_3338,buffer=500, fun=sum)
```
```{r}
copper_pop_3338$forest_cov<-100*forested_count/(20*20)
```

```{r}
ggplot() +
    geom_sf(data = copper_region_3338, aes(), color = "black") +
    geom_sf(data = copper_pop_3338, aes(color = forest_cov,
                                       size = population)) +
    scale_size_continuous(guide = F) +
    scale_colour_gradientn(colours = terrain.colors(10, rev=TRUE)) +
    theme_bw() +
    theme(legend.position = "bottom") +
    labs(color = "Percent Forest Cover")
```

