---
title: "Untitled"
author: "Mathieu Pruvot"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)
```
# Read in shapefile using sf
```{r}

ak_regions <- read_sf("data/ak_regions_simp.shp")

plot(ak_regions)  
class(ak_regions)  
head(ak_regions)

st_crs(ak_regions)
```
You can use [epsg.io](http://epsg.io/) to look up epsg online

```{r}
ak_regions_3338 <- ak_regions %>% #adding the number at the end avoids having to check st_crs all the time
  st_transform(crs = 3338)

st_crs(ak_regions_3338)
plot(ak_regions_3338)
```
sf object work in tidyverse such as:
```{r}
ak_regions_3338 %>% 
  filter(region=="Southeast") %>% #filter rows
  select(region) #select data column
```

#Spatial joins and summaries

```{r}
pop <-read.csv("data/alaska_population.csv",stringsAsFactors = F)
head(pop)
#use st_join to spatially join this data to the sf object

pop_4326 <- st_as_sf(pop,
                     coords= c('lng','lat'),
                     crs=4326,
                     remove=F) #do you want to keep coordinates in the data table?
```
```{r}
pop_joined <- pop_4326 %>% 
  st_transform(crs=3338) %>% 
  st_join(.,ak_regions_3338)
head(pop_joined)
plot(pop_joined)
```
## calculate population by region

```{r}
pop_region <- pop_joined %>% 
  as.data.frame() %>% #drops the geometry column, otherwise it keeps the object as grouped points
  group_by(region) %>% 
  summarise(total_pop=sum(population))

head(pop_region)
```

```{r}
pop_region_3338 <- left_join(ak_regions_3338, pop_region, by= "region")
plot(pop_region_3338)
```

```{r}
pop_mgmt_3338 <- pop_region_3338 %>% 
  group_by(mgmt_area) %>% 
  summarise(total_pop =sum(total_pop),do_union=T)
plot(pop_mgmt_3338[,"total_pop"])
```
## write .shp
```{r}
write_sf(pop_region_3338,"data/ak_region_pop.shp", delete_layer=T)
```

# Make map pretty
```{r}
rivers_3338 <- read_sf("data/ak_rivers_simp.dbf")
pop_3338 <-st_transform(pop_4326, crs=3338)
```


```{r}
ggplot()+
  geom_sf(data=pop_region_3338, aes(fill=total_pop)) + #add the data in the geom call because when creating maps, you add several layers
  geom_sf(data=pop_3338,size=0.5)+
  geom_sf(data=rivers_3338,aes(size=StrOrder),color="black")+
  scale_size(range =c(0.01, 0.2),guide=F)+ #this only applies to the river, if you need several size scales on multiple features, you need another package to handle it, or it will overwrite the first scale_size parameters
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low="khaki",high="firebrick", labels=comma) #custom color gradient; comma comes from the 'scales' package which convert to a nicer format

```

#Getting basemaps using ggmap


```{r}
pop_3857 = pop_3338 %>% 
st_transform(crs=3857)
```

```{r}
# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
```
```{r}
bbox <- c(-170,52,-130,64)
ak_map <- get_stamenmap(bbox,zoom=4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)

class(ak_map_3857)
```

```{r}
ggmap(ak_map_3857) +
  geom_sf(data=pop_3857, aes(color=population), inherit.aes = F) +#inherit.aes =F avoids bringing aes info from the ggmap call
  scale_color_continuous(low="khaki", high="firebrick")
```

# using leaflet

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
pop_region_4326 <- pop_region_3338 %>% 
  st_transform(crs = 4326)
```

```{r}
m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = "gray",
                    weight = 1)

m
```
```{r}
pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")

m
```

